name: Dodge Bot Daily

on:
  schedule:
    - cron: '*/5 * * * *'  # Каждые 5 минут (ТЕСТ)
    - cron: '0 7 * * *'    # 10:00 Moscow Time (7:00 UTC) - Утро
    - cron: '0 16 * * *'   # 19:00 Moscow Time (16:00 UTC) - Вечер
  workflow_dispatch:

jobs:
  send_morning:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.schedule == '0 7 * * *' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Morning Bot
        run: python dodge_bot.py morning

  send_evening:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.schedule == '0 16 * * *' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Evening Bot
        run: python dodge_bot.py evening
